// <auto-generated />
using AdvAPIPractice.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvAPIPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220914071605_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdvAPIPractice.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AdvertiserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvertiserId = 1,
                            Description = "iron hammer big",
                            ImageURL = "https://",
                            Size = "S"
                        },
                        new
                        {
                            Id = 2,
                            AdvertiserId = 1,
                            Description = "iron hammer small",
                            ImageURL = "https://",
                            Size = "M"
                        },
                        new
                        {
                            Id = 3,
                            AdvertiserId = 1,
                            Description = "plastic hammer big",
                            ImageURL = "https://",
                            Size = "L"
                        },
                        new
                        {
                            Id = 4,
                            AdvertiserId = 2,
                            Description = "metal umbrella cube",
                            ImageURL = "https://",
                            Size = "M"
                        });
                });

            modelBuilder.Entity("AdvAPIPractice.Models.Advertiser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advertisers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bauhaus"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Praktiker"
                        });
                });

            modelBuilder.Entity("AdvAPIPractice.Models.SizeLookUp", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("SizeType")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("SizeLookUp");

                    b.HasData(
                        new
                        {
                            Code = "S",
                            Description = "Small",
                            Height = 50,
                            SizeType = 0,
                            Width = 50
                        },
                        new
                        {
                            Code = "M",
                            Description = "Medium",
                            Height = 100,
                            SizeType = 1,
                            Width = 100
                        },
                        new
                        {
                            Code = "L",
                            Description = "Large",
                            Height = 200,
                            SizeType = 2,
                            Width = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
